#!/bin/sh

set -eu

exec 2>&1

file="/etc/sysconfig/tcedir/../bootattempt"
delay=30
max_attempts=2
partition=2

cmdline="$(cat /proc/cmdline)"

for i in $cmdline
do
	case $i in
		recovery.*=*)
			j=${i#*.}
			param=${j%=*}
			value=${j#*=}
			case $param in
				file|delay|max_attempts|partition)
					eval "${param}=\"${value}\""
					;;
				*)
					echo "Unexpected param: recovery.$param"
					;;
			esac
			;;
	esac
done


loop() {
	if [ ! -e "${file}" ]
	then
		echo "${file} doesn't exist - create it to start recovery auto boot"
		return 0
	fi

	ATTEMPT="$(cat "$file")"
	case "$ATTEMPT" in
		''|*[!0-9]*) ATTEMPT=0 ;;
	esac

	if [ "$ATTEMPT" -ge "$max_attempts" ]
	then
		echo "${ATTEMPT} boot attempt(s) failed, ${max_attempts} allowed - write 0 to ${file} to restart"
		return 0
	fi

	ACTUAL_DELAY="$(($delay*2**${ATTEMPT}))"
	echo "Booting partition $partition in $ACTUAL_DELAY seconds ..."
	sleep $ACTUAL_DELAY
	echo "$((ATTEMPT+1))" > "$file"
	sync
	echo "Booting now..."
	tryboot "$partition"
	sleep $delay
}

while true
do
	loop
	sleep 5
done
