#!/bin/sh

set -eu

exec 2>&1

SERVICE_DIR="$( cd "$(dirname $0)" && echo ${PWD} )"
SERVICE_NAME="${SERVICE_DIR##*/}"
DEVICE="${SERVICE_NAME##*.}"

while ! grep -q $DEVICE /proc/net/dev
do
	echo "Waiting for ${DEVICE}..."
	sleep 5
done

echo "Waiting for a bit..."
sleep 5

echo "Starting hostapd for ${DEVICE} on ap0"

iw phy phy0 interface add ap0 type __ap


# get current wpa channel:
CHANNEL="$(iw dev $DEVICE info | grep channel | awk '{print $2}')"

echo "${DEVICE} is using channel ${CHANNEL}"

# run hostapd
cat > /usr/local/etc/hostapd.conf <<HOSTAPDCONF
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
interface=ap0
driver=nl80211
ssid=test
hw_mode=g
# channel should match what wpa_supplicant is using
channel=$CHANNEL
wmm_enabled=0
macaddr_acl=0
auth_algs=1
wpa=2
wpa_passphrase=testtest123
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP CCMP
rsn_pairwise=CCMP
HOSTAPDCONF

exec hostapd /usr/local/etc/hostapd.conf
