#!/bin/sh

DEVICES="ttyAMA0"

for DEVICE in $DEVICES
do
	BASE="/usr/local/etc/init.d/services"
	SERVICE="service-serial"
	SERVICE_DIR="${BASE}/${SERVICE}"
	SERVICE_DEVICE="${SERVICE}.${DEVICE}"
	SERVICE_DEVICE_DIR="${BASE}/${SERVICE_DEVICE}"

	mkdir -p "${SERVICE_DEVICE_DIR}/log"
	ln -s "${SERVICE_DIR}/log/run" "${SERVICE_DEVICE_DIR}/log/run"
	ln -s "${SERVICE_DIR}/run" "${SERVICE_DEVICE_DIR}/run"

	runsv "${SERVICE_DEVICE_DIR}" &
done
