#!/bin/sh

set -eu

exec 2>&1

SERVICE_DIR="$( cd "$(dirname $0)" && echo ${PWD} )"
SERVICE_NAME="${SERVICE_DIR##*/}"
DEVICE="${SERVICE_NAME##*.}"

echo "Starting dhcp client for ${DEVICE}"

exec /sbin/udhcpc -f -i "$DEVICE" -x hostname:$(/bin/hostname)
