name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      PACKAGE: "piCore64"
      VERSION: "16.0.0"
      VERSION_ROOTFS: "16.0"
      VERSION_FAMILY: "16.x"
      ARCH: "aarch64"

    steps:
      - name: build
        run: |
          scripts/install.sh
