name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      PACKAGE: "piCore64"
      VERSION: "16.0.0"
      VERSION_ROOTFS: "16.0"
      VERSION_FAMILY: "16.x"
      ARCH: "aarch64"

    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/asssaf/piCore
          tags: type=raw,value=latest,priority=2000

      - name: Build and push builder image
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          push: false
          build-args: |
            PACKAGE: ${{ env.PACKAGE }}
            VERSION: ${{ env.VERSION }}
            VERSION_ROOTFS: ${{ env.VERSION_ROOTFS }}
            VERSION_FAMILY: ${{ env.VERSION_FAMILY }}
            ARCH: ${{ env.ARCH}}

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: build
        run: |
          scripts/install.sh
